openapi: 3.0.0
paths:
  /api/users/all:
    get:
      operationId: UsersRestController_getAllUsers
      parameters: []
      responses:
        "200":
          description: ""
  "/api/users/email/{email}":
    get:
      operationId: UsersRestController_getUserByEmail
      parameters:
        - name: email
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
  /metrics:
    get:
      operationId: PrometheusController_index
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: User query API
  description: "[CQRS] Query"
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas: {}
