app:
  port: 3001
  name: 'User query API'
  description: '[CQRS] Query'
  version: '1.0'
  document-path: '/api-doc'

log:
  level: 'silly'

nanoid:
  alphanum: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
  len: 11

api-services:
  photos:
    list-photo:
      url: https://self-signed.badssl.com/
      method: "GET"
      timeout: 5000
      reject-unauthorized: false

kafka:
  client:
    client-id: 'user-query'
    brokers:
      - '134.209.108.174:9092'
  consumer:
    group-id: 'user-query-consumer'
